---
- name: Install Git and configure defaults
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Update apt cache and install Git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Read current system init.defaultBranch
      command: git config --system --get init.defaultBranch
      register: current_default_branch
      failed_when: false
      changed_when: false

    - name: Ensure Git system init.defaultBranch is set to main
      git_config:
        scope: system
        name: init.defaultBranch
        value: main
      when: current_default_branch.stdout != "main"

    - name: Set global Git user email
      git_config:
        scope: global
        name: user.email
        value: "sudhansu.ace@gmail.com"
      become: no

    - name: Set global Git user name
      git_config:
        scope: global
        name: user.name
        value: "alphacrash"
      become: no
